---
- name: Validate variables
  action: validate_vars

- import_tasks: deps.yml

- import_tasks: peertube.yml

- import_tasks: webserver.yml

- name: database tasks
  become: yes
  become_user: postgres
  import_tasks: database.yml

- import_tasks: s3.yml

